### ISSUE TITLE
Create live script to run OpticalCritical example

### ISSUE THREAD

**Issue by gcapes** [zan8simone/PPML---Periodically-Patterned-Multi-Layer#2]
- [x] For speed of execution, could reduce the number of incidence angles to e.g. 5. This would need to be presented differently rather than the existing image plot
- [x] Add live script controls for user to change lambda (stripe spacing), and depth (h)
- [x] Separate plotting code out of the `optical_critical` function

**Comment by gcapes** [comment]
@zan8simone 
Could you please clarify how lambda is represented in the code? I think maybe the terminology is different to the paper you showed? It is `f.a` from fig 1.a of the manual?

**Comment by zan8simone** [comment]
Hi, what is "lambda" in the paper, is named "a" in the manual and "a" in the code.

**Comment by gcapes** [comment]
The original 55 incidence angles takes around 42 seconds to run on my machine, whereas 5 angles takes ~3s. I've plotted these 5 angles using the original image plot, and again as a tiled layout. What are your thoughts as to the best way to display the results?

![imageplot55](https://github.com/zan8simone/PPML---Periodically-Patterned-Multi-Layer/assets/12446270/24b36d04-97da-4c2d-88c1-fb6974f70c4b)

![imageplot05](https://github.com/zan8simone/PPML---Periodically-Patterned-Multi-Layer/assets/12446270/546df6b3-b905-43ae-ac70-95bc4c4dceca)

![slices](https://github.com/zan8simone/PPML---Periodically-Patterned-Multi-Layer/assets/12446270/fbdf6c51-50d6-41df-b3a9-9bfafe392425)

**Comment by gcapes** [comment]
Perhaps there could be a threshold for plotting < 10(?) angles as a tiled layout, and more than that as an image plot?
Either way I think the plotting code might be best separated out of the `optical_critical` function
