### ISSUE TITLE
Create GUI to generate arrays for material properties

### ISSUE THREAD

**Issue by gcapes** [zan8simone/PPML---Periodically-Patterned-Multi-Layer#4]
This is currently [done manually](https://github.com/zan8simone/PPML---Periodically-Patterned-Multi-Layer/blob/main/examples/OpticalCritical_APL2013_fig3_a.m#L56)

**Comment by gcapes** [comment]
It would be handy if this could link in with [refractiveindex.info](https://refractiveindex.info/)

**Comment by gcapes** [comment]
@zan8simone 
It would be handy if I could have a refresher on exactly what is required for this issue.

**Comment by gcapes** [comment]
After discussion today we suggested maybe a change of direction to generating a graphical representation of the arrays as a visual check that the properties have been correctly set.

**Comment by gcapes** [comment]
@zan8simone 
Could I just check that we're talking about recreating figure 1a from the manual?

So we'd have a substrate, L internal layers, and a superstrate.
The diagram should be of width a, showing the fraction of material B mixed in with material A.
This is depicted as a slice of B within A, for each of the internal layers.

Is that more or less the task in question?
Thanks!

**Comment by zan8simone** [comment]
Yes, exactly!
